### PR TITLE
Update Forecast.io to Dark Sky

### PR DESCRIPTION
**Pull request by jeffbyrnes**
@jason0x43 so @darkskyapp renamed/rebranded to bring the Forecast.io site/API back under the main company/app name, [Dark Sky](https://darksky.net).

This updates all the copy, method/constant/variable names, and URLs, to follow suit.

I’ve tested this with my local copy of the workflow, and it works great.

### CODE REVIEW

**Comment by jason0x43** [comment]
Please note that this workflow is no longer maintained. A new version of the workflow that uses the Dark Sky API is available [here](https://github.com/jason0x43/alfred-weather).

**Comment by jeffbyrnes** [comment]
@jason0x43 oh! Well alrighty then. Decided to rewrite it in Go, I see, nice. Thanks for adding a deprecation notice in d2b14601a73f087d532aaaafd2402ef37e8640c7.

**Comment by jason0x43** [comment]
Yeah, I started the rewrite months ago (I converted my other workflows to Go a while back), but I just recently managed to finish it up.

**Comment by jeffbyrnes** [comment]
@jason0x43 nice. Well thanks for it, it’s a great rewrite! Gotta retrain my fingers to type the new commands.

**Pull request closed without merging**
